# Snowflake Notebook 環境設定
# このファイルはNotebookと同じディレクトリに配置することで
# 自動的にパッケージがインストールされます

name: mlops_handson
channels:
  - snowflake
dependencies:
  - snowflake-ml-python
  - shap
  - matplotlib
  - seaborn        # Confusion Matrix可視化用
  - xgboost
  - scikit-learn
  - scipy

